# Generated by Django 4.1.13 on 2026-04-04 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('allergies', models.TextField(blank=True)),
                ('previous_injuries', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('display_name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='PortalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('password_updated_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_account', to='system.person')),
            ],
            options={
                'ordering': ('person__full_name',),
            },
        ),
        migrations.CreateModel(
            name='PortalPasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default='', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('access_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to='system.portalaccount')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PersonTypeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_assignments', to='system.person')),
                ('person_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_assignments', to='system.persontype')),
            ],
            options={
                'ordering': ('person__full_name', 'person_type__display_name'),
            },
        ),
        migrations.CreateModel(
            name='PersonRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_kind', models.CharField(choices=[('responsible_for', 'Responsável por')], default='responsible_for', max_length=40)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('source_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='system.person')),
                ('target_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='system.person')),
            ],
            options={
                'ordering': ('source_person__full_name', 'target_person__full_name'),
            },
        ),
        migrations.AddField(
            model_name='person',
            name='person_types',
            field=models.ManyToManyField(related_name='people', through='system.PersonTypeAssignment', to='system.persontype'),
        ),
        migrations.AddConstraint(
            model_name='persontypeassignment',
            constraint=models.UniqueConstraint(fields=('person', 'person_type'), name='unique_person_type_assignment'),
        ),
        migrations.AddConstraint(
            model_name='personrelationship',
            constraint=models.UniqueConstraint(fields=('source_person', 'target_person', 'relationship_kind'), name='unique_person_relationship'),
        ),
        migrations.AddConstraint(
            model_name='personrelationship',
            constraint=models.CheckConstraint(check=models.Q(('source_person', models.F('target_person')), _negated=True), name='prevent_self_person_relationship'),
        ),
    ]
