# Generated by Django 4.1.13 on 2026-04-10 11:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('display_name', models.CharField(max_length=80, unique=True)),
                ('audience', models.CharField(choices=[('adult', 'Adulto'), ('juvenile', 'Juvenil'), ('kids', 'Kids'), ('women', 'Feminino')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'display_name'),
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_capacity', models.PositiveIntegerField(default=0)),
                ('class_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='system.classcategory')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.CharField(choices=[('monday', 'Segunda-feira'), ('tuesday', 'Terça-feira'), ('wednesday', 'Quarta-feira'), ('thursday', 'Quinta-feira'), ('friday', 'Sexta-feira'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], max_length=12)),
                ('training_style', models.CharField(choices=[('gi', 'Kimono'), ('no_gi', 'Sem kimono'), ('mixed', 'Misto')], default='mixed', max_length=12)),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='system.classgroup')),
            ],
            options={
                'ordering': ('class_group__display_name', 'display_order', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='IbjjfAgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('display_name', models.CharField(max_length=120, unique=True)),
                ('audience', models.CharField(choices=[('adult', 'Adulto'), ('juvenile', 'Juvenil'), ('kids', 'Kids'), ('women', 'Feminino')], max_length=16)),
                ('minimum_age', models.PositiveIntegerField()),
                ('maximum_age', models.PositiveIntegerField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'minimum_age', 'display_name'),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('biological_sex', models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Feminino')], max_length=16)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('allergies', models.TextField(blank=True)),
                ('previous_injuries', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=255)),
                ('martial_art', models.CharField(blank=True, choices=[('jiu_jitsu', 'Jiu Jitsu'), ('muay_thai', 'Muay Thai'), ('judo', 'Judô'), ('karate', 'Karatê'), ('boxing', 'Boxe'), ('wrestling', 'Wrestling'), ('other', 'Outra')], max_length=24)),
                ('martial_art_graduation', models.CharField(blank=True, max_length=120)),
                ('jiu_jitsu_belt', models.CharField(blank=True, choices=[('white', 'Branca'), ('blue', 'Azul'), ('purple', 'Roxa'), ('brown', 'Marrom'), ('black', 'Preta'), ('red_black', 'Vermelha e Preta'), ('red_white', 'Vermelha e Branca'), ('red', 'Vermelha')], max_length=24)),
                ('jiu_jitsu_stripes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('class_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='system.classcategory')),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='system.classgroup')),
                ('class_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='system.classschedule')),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('display_name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='PortalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('password_updated_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_account', to='system.person')),
            ],
            options={
                'ordering': ('person__full_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=60, unique=True, verbose_name='SKU')),
                ('display_name', models.CharField(max_length=200, verbose_name='Nome')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço unitário')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ('category__display_order', 'display_name'),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de produto',
                'verbose_name_plural': 'Categorias de produto',
                'ordering': ('display_order', 'display_name'),
            },
        ),
        migrations.CreateModel(
            name='RegistrationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço do plano')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_orders', to='system.person', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Pedido de matrícula',
                'verbose_name_plural': 'Pedidos de matrícula',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='Código')),
                ('display_name', models.CharField(max_length=200, verbose_name='Nome')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], default='monthly', max_length=20, verbose_name='Ciclo de cobrança')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Plano de assinatura',
                'verbose_name_plural': 'Planos de assinatura',
                'ordering': ('display_order', 'price'),
            },
        ),
        migrations.CreateModel(
            name='RegistrationOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=200, verbose_name='Nome do produto')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unitário')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='system.registrationorder', verbose_name='Pedido')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='system.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do pedido',
                'verbose_name_plural': 'Itens do pedido',
                'ordering': ('pk',),
            },
        ),
        migrations.AddField(
            model_name='registrationorder',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_orders', to='system.subscriptionplan', verbose_name='Plano'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(blank=True, default='', max_length=20, verbose_name='Tamanho')),
                ('color', models.CharField(blank=True, default='', max_length=60, verbose_name='Cor')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Estoque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='system.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Variante de produto',
                'verbose_name_plural': 'Variantes de produto',
                'ordering': ('color', 'size'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='system.productcategory', verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='PortalPasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default='', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('access_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to='system.portalaccount')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PersonRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_kind', models.CharField(choices=[('responsible_for', 'Responsável por')], default='responsible_for', max_length=40)),
                ('kinship_type', models.CharField(blank=True, max_length=24)),
                ('kinship_other_label', models.CharField(blank=True, max_length=80)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('source_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='system.person')),
                ('target_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='system.person')),
            ],
            options={
                'ordering': ('source_person__full_name', 'target_person__full_name'),
            },
        ),
        migrations.AddField(
            model_name='person',
            name='person_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='system.persontype'),
        ),
        migrations.CreateModel(
            name='ClassInstructorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_assignments', to='system.classgroup')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_instructor_assignments', to='system.person')),
            ],
            options={
                'ordering': ('class_group__display_name', 'person__full_name'),
            },
        ),
        migrations.AddField(
            model_name='classgroup',
            name='main_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_class_groups', to='system.person'),
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('paused', 'Pausada'), ('cancelled', 'Cancelada')], default='active', max_length=16)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='system.classgroup')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to='system.person')),
            ],
            options={
                'ordering': ('class_group__display_name', 'person__full_name'),
            },
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'size', 'color'), name='unique_product_variant'),
        ),
        migrations.AddConstraint(
            model_name='personrelationship',
            constraint=models.UniqueConstraint(fields=('source_person', 'target_person', 'relationship_kind'), name='unique_person_relationship'),
        ),
        migrations.AddConstraint(
            model_name='personrelationship',
            constraint=models.CheckConstraint(check=models.Q(('source_person', models.F('target_person')), _negated=True), name='prevent_self_person_relationship'),
        ),
        migrations.AddConstraint(
            model_name='classschedule',
            constraint=models.UniqueConstraint(fields=('class_group', 'weekday', 'training_style', 'start_time'), name='unique_class_schedule_slot'),
        ),
        migrations.AddConstraint(
            model_name='classinstructorassignment',
            constraint=models.UniqueConstraint(fields=('class_group', 'person'), name='unique_class_instructor_assignment'),
        ),
        migrations.AddConstraint(
            model_name='classenrollment',
            constraint=models.UniqueConstraint(fields=('class_group', 'person'), name='unique_class_enrollment'),
        ),
    ]
