# Generated by Django 4.1.13 on 2026-04-01 17:51

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.CharField(default='default', editable=False, max_length=32, unique=True)),
                ('academy_name', models.CharField(default='LV JIU JITSU', max_length=120)),
                ('hero_title', models.CharField(default='Jiu-Jitsu com metodo, disciplina e comunidade.', max_length=160)),
                ('hero_subtitle', models.TextField(default='Construa constancia, evolucao tecnica e confianca em um ambiente acolhedor para iniciantes e atletas.')),
                ('public_whatsapp', models.CharField(blank=True, max_length=32)),
                ('public_email', models.EmailField(blank=True, max_length=254)),
                ('public_instagram', models.CharField(blank=True, max_length=120)),
                ('public_address', models.CharField(blank=True, max_length=255)),
                ('dependent_credential_min_age', models.PositiveSmallIntegerField(default=12)),
                ('qr_code_ttl_seconds', models.PositiveIntegerField(default=60)),
                ('late_arrival_tolerance_minutes', models.PositiveIntegerField(default=10)),
                ('trial_class_minimum_notice_hours', models.PositiveIntegerField(default=4)),
                ('allow_trial_without_guardian', models.BooleanField(default=False)),
                ('public_notice', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Academy Configuration',
                'verbose_name_plural': 'Academy Configuration',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('source', models.CharField(choices=[('landing', 'Landing'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('referral', 'Indicacao'), ('walkin', 'Presencial')], default='landing', max_length=32)),
                ('interest_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Novo'), ('contacted', 'Em contato'), ('converted', 'Convertido'), ('archived', 'Arquivado')], default='new', max_length=24)),
                ('converted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PublicClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.CharField(max_length=80)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Segunda'), (2, 'Terca'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sabado'), (7, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('instructor_name', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('weekday', 'start_time', 'display_order'),
            },
        ),
        migrations.CreateModel(
            name='PublicPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('summary', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], default='monthly', max_length=16)),
                ('cta_label', models.CharField(default='Quero saber mais', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.AlterField(
            model_name='authenticationevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failure', 'Login Failure'), ('logout', 'Logout'), ('password_reset_request', 'Password Reset Request'), ('password_reset_success', 'Password Reset Success'), ('first_access_request', 'First Access Request'), ('first_access_success', 'First Access Success')], max_length=64),
        ),
        migrations.CreateModel(
            name='TrialClassRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_date', models.DateField()),
                ('preferred_period', models.CharField(choices=[('morning', 'Manha'), ('afternoon', 'Tarde'), ('evening', 'Noite')], max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('confirmed', 'Confirmada'), ('completed', 'Concluida'), ('cancelled', 'Cancelada')], default='requested', max_length=24)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_class_requests', to='system.lead')),
            ],
            options={
                'ordering': ('preferred_date', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='requested_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='system.publicplan'),
        ),
    ]
