# Generated by Django 4.1.13 on 2026-04-17 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationorder',
            name='administrative_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa administrativa'),
        ),
        migrations.AddField(
            model_name='registrationorder',
            name='deposit_status',
            field=models.CharField(choices=[('pending', 'A receber'), ('available', 'Disponível'), ('deposited', 'Depositado'), ('not_applicable', 'Não aplicável')], default='pending', max_length=20, verbose_name='Status de crédito'),
        ),
        migrations.AddField(
            model_name='registrationorder',
            name='deposited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Depositado em'),
        ),
        migrations.AddField(
            model_name='registrationorder',
            name='expected_deposit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de crédito'),
        ),
        migrations.AddField(
            model_name='registrationorder',
            name='financial_transaction_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ID da transação financeira'),
        ),
        migrations.AddField(
            model_name='registrationorder',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor líquido'),
        ),
        migrations.AddField(
            model_name='registrationorder',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('', 'Não definido'), ('asaas', 'Asaas'), ('stripe', 'Stripe'), ('manual', 'Manual')], default='', max_length=16, verbose_name='Gateway'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_family_plan',
            field=models.BooleanField(default=False, verbose_name='Plano familiar'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='monthly_reference_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço mensal de referência'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='payment_method',
            field=models.CharField(choices=[('pix', 'PIX'), ('credit_card', 'Cartão de crédito')], default='credit_card', max_length=16, verbose_name='Meio de pagamento'),
        ),
    ]
