# Generated by Django 4.1.13 on 2026-04-01 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_academyconfiguration_lead_publicclassschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('context', models.CharField(choices=[('onboarding', 'Onboarding'), ('profile', 'Perfil')], max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-accepted_at',),
            },
        ),
        migrations.CreateModel(
            name='ConsentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('audience', models.CharField(choices=[('all', 'Todos'), ('guardian', 'Responsavel'), ('student', 'Aluno')], default='all', max_length=24)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('required_for_onboarding', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('code', '-version'),
            },
        ),
        migrations.AlterField(
            model_name='authenticationevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failure', 'Login Failure'), ('logout', 'Logout'), ('password_reset_request', 'Password Reset Request'), ('password_reset_success', 'Password Reset Success'), ('first_access_request', 'First Access Request'), ('first_access_success', 'First Access Success'), ('profile_update', 'Profile Update'), ('password_change', 'Password Change')], max_length=64),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_type', models.CharField(choices=[('holder', 'Titular'), ('dependent', 'Dependente')], max_length=16)),
                ('operational_status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACTIVE', 'Ativo'), ('PENDING_FINANCIAL', 'Pendente Financeiro'), ('PAUSED', 'Pausado'), ('BLOCKED', 'Bloqueado'), ('INACTIVE', 'Inativo')], default='PENDING', max_length=32)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('join_date', models.DateField(default=django.utils.timezone.localdate)),
                ('self_service_access', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__full_name', 'user__cpf'),
            },
        ),
        migrations.CreateModel(
            name='SensitiveAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_type', models.CharField(choices=[('emergency_view', 'Consulta de prontuario'), ('emergency_update', 'Atualizacao de prontuario'), ('consent_view', 'Consulta de consentimentos')], max_length=32)),
                ('access_purpose', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensitive_access_logs', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitive_access_logs', to='system.studentprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LgpdRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('ACCESS', 'Acesso'), ('CORRECTION', 'Correcao'), ('ANONYMIZATION', 'Anonimizacao'), ('DELETION', 'Eliminacao')], max_length=24)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em andamento'), ('COMPLETED', 'Concluido'), ('REJECTED', 'Recusado')], default='OPEN', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgpd_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GuardianRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('self', 'Proprio'), ('parent', 'Responsavel'), ('mother', 'Mae'), ('father', 'Pai'), ('guardian', 'Guardiao legal'), ('spouse', 'Conjuge'), ('other', 'Outro')], max_length=24)),
                ('is_financial_responsible', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_links_as_responsible', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='system.studentprofile')),
            ],
            options={
                'ordering': ('student__user__full_name', 'responsible_user__full_name'),
            },
        ),
        migrations.CreateModel(
            name='EmergencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_phone', models.CharField(max_length=32)),
                ('emergency_contact_relationship', models.CharField(max_length=128)),
                ('blood_type', models.CharField(blank=True, max_length=16)),
                ('allergies', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('medical_notes', models.TextField(blank=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_record', to='system.studentprofile')),
            ],
            options={
                'ordering': ('student__user__full_name',),
            },
        ),
        migrations.AddConstraint(
            model_name='consentterm',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='uniq_consent_term_version'),
        ),
        migrations.AddField(
            model_name='consentacceptance',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='system.consentterm'),
        ),
        migrations.AddField(
            model_name='consentacceptance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_acceptances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='guardianrelationship',
            constraint=models.UniqueConstraint(fields=('responsible_user', 'student', 'start_date'), name='uniq_guardian_relationship_period'),
        ),
        migrations.AddConstraint(
            model_name='consentacceptance',
            constraint=models.UniqueConstraint(fields=('user', 'term'), name='uniq_user_term_acceptance'),
        ),
    ]
