# Generated by Django 4.1.13 on 2026-04-01 19:21

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import system.models.finance_models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_classreservation_physicalattendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('benefit_type', models.CharField(choices=[('DISCOUNT', 'Desconto'), ('SCHOLARSHIP', 'Bolsa'), ('OTHER', 'Outro')], max_length=16)),
                ('value_type', models.CharField(choices=[('PERCENTAGE', 'Percentual'), ('FIXED', 'Valor fixo')], max_length=16)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FinancialPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Mensal'), ('QUARTERLY', 'Trimestral'), ('SEMIANNUAL', 'Semestral'), ('ANNUAL', 'Anual')], max_length=16)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('allows_pause', models.BooleanField(default=True)),
                ('blocks_checkin_on_overdue', models.BooleanField(default=True)),
                ('active_from', models.DateField(default=django.utils.timezone.localdate)),
                ('active_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LocalSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('ACTIVE', 'Ativa'), ('PENDING_FINANCIAL', 'Pendente financeiro'), ('PAUSED', 'Pausada'), ('BLOCKED', 'Bloqueada'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=32)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('benefit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='system.financialbenefit')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='system.financialplan')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MonthlyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_month', models.DateField()),
                ('due_date', models.DateField()),
                ('amount_gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('OPEN', 'Aberta'), ('PAID', 'Paga'), ('OVERDUE', 'Vencida'), ('UNDER_REVIEW', 'Em analise'), ('CANCELLED', 'Cancelada')], default='OPEN', max_length=16)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='system.localsubscription')),
            ],
            options={
                'ordering': ('-reference_month', '-due_date'),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary_student', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_links', to='system.studentprofile')),
                ('student_benefit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_students', to='system.financialbenefit')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_students', to='system.localsubscription')),
            ],
            options={
                'ordering': ('subscription', 'student__user__full_name'),
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=system.models.finance_models.payment_proof_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UNDER_REVIEW', 'Em analise'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Reprovado')], default='UNDER_REVIEW', max_length=16)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='system.monthlyinvoice')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payment_proofs', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_payment_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='EnrollmentPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=255)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_pauses', to='system.studentprofile')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pauses', to='system.localsubscription')),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.AddConstraint(
            model_name='subscriptionstudent',
            constraint=models.UniqueConstraint(fields=('subscription', 'student'), name='uniq_subscription_student_link'),
        ),
        migrations.AddConstraint(
            model_name='monthlyinvoice',
            constraint=models.UniqueConstraint(fields=('subscription', 'reference_month'), name='uniq_subscription_invoice_month'),
        ),
    ]
