# Generated by Django 4.1.13 on 2026-04-01 21:57

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_financialbenefit_financialplan_localsubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_customer_id', models.CharField(max_length=64, unique=True)),
                ('livemode', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__full_name',),
            },
        ),
        migrations.CreateModel(
            name='StripePlanPriceMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_product_id', models.CharField(max_length=64)),
                ('stripe_price_id', models.CharField(max_length=64, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('lookup_key', models.CharField(blank=True, max_length=128)),
                ('currency', models.CharField(default='brl', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('recurring_interval', models.CharField(blank=True, max_length=16)),
                ('recurring_interval_count', models.PositiveSmallIntegerField(default=1)),
                ('livemode', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_current', models.BooleanField(default=False)),
                ('is_legacy', models.BooleanField(default=False)),
                ('supports_pause_collection', models.BooleanField(default=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_price_maps', to='system.financialplan')),
            ],
            options={
                'ordering': ('plan__name', '-is_current', '-valid_from'),
            },
        ),
        migrations.CreateModel(
            name='WebhookProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_event_id', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('RECEIVED', 'Recebido'), ('PROCESSED', 'Processado'), ('SKIPPED', 'Ignorado'), ('FAILED', 'Falhou')], default='RECEIVED', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processing_attempts', models.PositiveIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_verified', models.BooleanField(default=False)),
                ('livemode', models.BooleanField(default=False)),
                ('failure_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StripeSubscriptionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_subscription_id', models.CharField(max_length=64, unique=True)),
                ('stripe_status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACTIVE', 'Ativa'), ('PAST_DUE', 'Past due'), ('PAUSED_COLLECTION', 'Pausa de cobranca'), ('CANCELLED', 'Cancelada'), ('UNKNOWN', 'Desconhecida')], default='PENDING', max_length=32)),
                ('pause_collection_behavior', models.CharField(blank=True, max_length=32)),
                ('pause_collection_resumes_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('livemode', models.BooleanField(default=False)),
                ('latest_payload', models.JSONField(blank=True, default=dict)),
                ('customer_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_links', to='system.stripecustomerlink')),
                ('local_subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_subscription_link', to='system.localsubscription')),
                ('price_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_links', to='system.stripeplanpricemap')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CheckoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('CREATED', 'Criada'), ('SESSION_CREATED', 'Sessao criada'), ('COMPLETED', 'Concluida'), ('EXPIRED', 'Expirada'), ('FAILED', 'Falhou')], default='CREATED', max_length=32)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=64, null=True)),
                ('success_url', models.URLField()),
                ('cancel_url', models.URLField()),
                ('checkout_url', models.URLField(blank=True)),
                ('metadata_snapshot', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_message', models.TextField(blank=True)),
                ('customer_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_requests', to='system.stripecustomerlink')),
                ('local_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_requests', to='system.localsubscription')),
                ('price_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_requests', to='system.stripeplanpricemap')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='stripeplanpricemap',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_current', True)), fields=('plan',), name='uniq_active_current_price_map_per_plan'),
        ),
    ]
