# Generated by Django 4.1.13 on 2026-04-02 13:46

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_stripecustomerlink_stripeplanpricemap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardDailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField(unique=True)),
                ('active_students_count', models.PositiveIntegerField(default=0)),
                ('pending_financial_students_count', models.PositiveIntegerField(default=0)),
                ('paid_revenue_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('attendances_count', models.PositiveIntegerField(default=0)),
                ('cancelled_subscriptions_count', models.PositiveIntegerField(default=0)),
                ('active_pauses_count', models.PositiveIntegerField(default=0)),
                ('overdue_invoices_count', models.PositiveIntegerField(default=0)),
                ('under_review_proofs_count', models.PositiveIntegerField(default=0)),
                ('requested_trial_classes_count', models.PositiveIntegerField(default=0)),
                ('pending_checkout_requests_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-snapshot_date',),
            },
        ),
    ]
