# Generated by Django 4.1.13 on 2026-04-02 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_dashboarddailysnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('scheduled_for', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('COMPLETED', 'Concluido'), ('CANCELLED', 'Cancelado')], default='OPEN', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduation_exams', to='system.classgroup')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_graduation_exams', to=settings.AUTH_USER_MODEL)),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduation_exams', to='system.classdiscipline')),
            ],
            options={
                'ordering': ('-scheduled_for', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='GraduationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('OFFICIAL', 'Referencia oficial'), ('INTERNAL', 'Regra interna da academia')], max_length=16)),
                ('current_degree', models.PositiveSmallIntegerField(default=0)),
                ('target_degree', models.PositiveSmallIntegerField(default=0)),
                ('minimum_active_days', models.PositiveIntegerField(default=0)),
                ('minimum_attendances', models.PositiveIntegerField(default=0)),
                ('minimum_age', models.PositiveIntegerField(default=0)),
                ('maximum_inactivity_days', models.PositiveIntegerField(default=45)),
                ('requires_exam', models.BooleanField(default=True)),
                ('criteria_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_belt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_rules_as_current', to='system.ibjjfbelt')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduation_rules', to='system.classdiscipline')),
                ('target_belt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_rules_as_target', to='system.ibjjfbelt')),
            ],
            options={
                'ordering': ('scope', 'current_belt__display_order', 'current_degree', 'target_belt__display_order', 'target_degree'),
            },
        ),
        migrations.CreateModel(
            name='GraduationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree_level', models.PositiveSmallIntegerField(default=0)),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('event_type', models.CharField(choices=[('INITIAL', 'Inicio da jornada'), ('PROMOTION', 'Promocao'), ('MANUAL', 'Ajuste manual')], default='INITIAL', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('belt_rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graduation_histories', to='system.ibjjfbelt')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_graduation_histories', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_histories', to='system.studentprofile')),
            ],
            options={
                'ordering': ('student__user__full_name', '-started_on', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='GraduationExamParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_degree', models.PositiveSmallIntegerField(default=0)),
                ('suggested_degree', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('POSTPONED', 'Adiado'), ('REJECTED', 'Nao aprovado')], default='PENDING', max_length=16)),
                ('eligibility_snapshot', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('certificate_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('certificate_issued_at', models.DateTimeField(blank=True, null=True)),
                ('current_belt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graduation_exam_participations_as_current', to='system.ibjjfbelt')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduation_exam_decisions', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='system.graduationexam')),
                ('promoted_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_participations', to='system.graduationhistory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_exam_participations', to='system.studentprofile')),
                ('suggested_belt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graduation_exam_participations_as_suggested', to='system.ibjjfbelt')),
            ],
            options={
                'ordering': ('student__user__full_name',),
            },
        ),
        migrations.AddConstraint(
            model_name='graduationrule',
            constraint=models.UniqueConstraint(fields=('scope', 'discipline', 'current_belt', 'current_degree'), name='uniq_graduation_rule_scope_stage'),
        ),
        migrations.AddConstraint(
            model_name='graduationrule',
            constraint=models.UniqueConstraint(condition=models.Q(('discipline__isnull', True)), fields=('scope', 'current_belt', 'current_degree'), name='uniq_graduation_rule_scope_stage_generic'),
        ),
        migrations.AddConstraint(
            model_name='graduationhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('student',), name='uniq_current_graduation_history_per_student'),
        ),
        migrations.AddConstraint(
            model_name='graduationexamparticipation',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='uniq_graduation_exam_student'),
        ),
    ]
