# Generated by Django 4.1.13 on 2026-04-02 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import system.models.lgpd_models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_graduationexam_graduationrule_graduationhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('audience', models.CharField(choices=[('ALL_USERS', 'Todos os usuarios'), ('ACTIVE_STUDENTS', 'Alunos ativos com acesso'), ('ACTIVE_HOUSEHOLDS', 'Familias ativas'), ('INSTRUCTORS', 'Professores'), ('STAFF', 'Equipe administrativa'), ('PENDING_FINANCIAL', 'Financeiro pendente')], default='ALL_USERS', max_length=32)),
                ('channel', models.CharField(choices=[('PORTAL', 'Portal'), ('EMAIL', 'E-mail')], max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('QUEUED', 'Na fila'), ('SENT', 'Enviado'), ('PARTIAL', 'Parcial'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=16)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_stats', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bulk_communications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='consentterm',
            name='attachment',
            field=models.FileField(blank=True, upload_to=system.models.lgpd_models.consent_term_attachment_upload_to),
        ),
        migrations.AddField(
            model_name='lgpdrequest',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=48, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lgpdrequest',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lgpdrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_lgpd_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lgpdrequest',
            name='processing_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lgpdrequest',
            name='result_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='NoticeBoardMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('ALL_USERS', 'Todos os usuarios'), ('ACTIVE_STUDENTS', 'Alunos ativos com acesso'), ('ACTIVE_HOUSEHOLDS', 'Familias ativas'), ('INSTRUCTORS', 'Professores'), ('STAFF', 'Equipe administrativa'), ('PENDING_FINANCIAL', 'Financeiro pendente')], default='ALL_USERS', max_length=32)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notice_board_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-starts_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='DocumentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Contrato'), ('AUTHORIZATION', 'Autorizacao'), ('MEDICAL', 'Documento medico'), ('OTHER', 'Outro')], default='OTHER', max_length=24)),
                ('title', models.CharField(max_length=255)),
                ('version_label', models.CharField(blank=True, max_length=64)),
                ('file', models.FileField(upload_to=system.models.lgpd_models.document_record_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_visible_to_owner', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_records', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_records', to='system.studentprofile')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_records', to='system.localsubscription')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_document_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-issued_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CommunicationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('PORTAL', 'Portal'), ('EMAIL', 'E-mail')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SENT', 'Enviado'), ('FAILED', 'Falhou'), ('SKIPPED', 'Ignorado')], default='PENDING', max_length=16)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='system.bulkcommunication')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('recipient_user__full_name',),
            },
        ),
        migrations.AddConstraint(
            model_name='communicationdelivery',
            constraint=models.UniqueConstraint(fields=('communication', 'recipient_user', 'channel'), name='uniq_delivery_per_user_channel'),
        ),
    ]
