# Generated by Django 4.1.13 on 2026-04-02 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_cashsession_pdvproduct_pdvsale_pdvsaleitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvExportControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('control_file_path', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('last_validation_status', models.CharField(blank=True, choices=[('VALID', 'Valido'), ('INVALID', 'Invalido'), ('ERROR', 'Erro')], max_length=16)),
                ('last_validation_message', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('ATTENDANCE', 'Presenca'), ('FINANCE', 'Financeiro'), ('GRADUATION', 'Graduacao'), ('AUDIT', 'Auditoria')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SUCCEEDED', 'Concluido'), ('FAILED', 'Falhou')], default='PENDING', max_length=16)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('AUTH', 'Autenticacao'), ('FINANCE', 'Financeiro'), ('PAYMENTS', 'Pagamentos'), ('ATTENDANCE', 'Presenca'), ('GRADUATION', 'Graduacao'), ('DOCUMENTS', 'Documentos'), ('EMERGENCY', 'Emergencia'), ('PDV', 'PDV'), ('REPORTS', 'Relatorios'), ('SYSTEM', 'Sistema')], max_length=32)),
                ('action', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('SUCCESS', 'Sucesso'), ('FAILURE', 'Falha')], default='SUCCESS', max_length=16)),
                ('target_model', models.CharField(blank=True, max_length=64)),
                ('target_uuid', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
