ROLE_ADMIN_MASTER = "ADMIN_MASTER"
ROLE_ADMIN_UNIDADE = "ADMIN_UNIDADE"
ROLE_RECEPCAO = "RECEPCAO"
ROLE_PROFESSOR = "PROFESSOR"
ROLE_ALUNO_TITULAR = "ALUNO_TITULAR"
ROLE_ALUNO_DEPENDENTE_COM_CREDENCIAL = "ALUNO_DEPENDENTE_COM_CREDENCIAL"
ROLE_RESPONSAVEL_FINANCEIRO = "RESPONSAVEL_FINANCEIRO"

ROLE_CHOICES = (
    ROLE_ADMIN_MASTER,
    ROLE_ADMIN_UNIDADE,
    ROLE_RECEPCAO,
    ROLE_PROFESSOR,
    ROLE_ALUNO_TITULAR,
    ROLE_ALUNO_DEPENDENTE_COM_CREDENCIAL,
    ROLE_RESPONSAVEL_FINANCEIRO,
)

PASSWORD_ACTION_FIRST_ACCESS = "first_access"
PASSWORD_ACTION_RESET = "password_reset"
