from django.urls import path

from system.views import (
    AdminBackorderQueueView,
    AdminCalendarView,
    AdminHomeView,
    AdminSpecialClassCreateView,
    AdminSpecialClassDeleteView,
    AdminToggleSessionView,
    AdministrativeHomeView,
    ClassCategoryCreateView,
    ClassCategoryDeleteView,
    ClassCategoryDetailView,
    ClassCategoryListView,
    ClassCategoryUpdateView,
    ClassGroupCreateView,
    ClassGroupDeleteView,
    ClassGroupDetailView,
    ClassGroupListView,
    ClassGroupUpdateView,
    ClassScheduleCreateView,
    ClassScheduleDeleteView,
    ClassScheduleDetailView,
    ClassScheduleListView,
    ClassScheduleUpdateView,
    ApprovalQueueView,
    BeltRankCreateView,
    BeltRankDeleteView,
    BeltRankDetailView,
    BeltRankListView,
    BeltRankUpdateView,
    GraduationCreateView,
    GraduationDeleteView,
    GraduationListView,
    GraduationOverviewView,
    GraduationRuleCreateView,
    GraduationRuleDeleteView,
    GraduationRuleListView,
    GraduationRuleUpdateView,
    InstructorApproveCheckinView,
    InstructorApproveSpecialCheckinView,
    InstructorCalendarView,
    InstructorSpecialClassCreateView,
    InstructorSpecialClassDeleteView,
    InstructorToggleSessionView,
    CancelMembershipActionView,
    ChangeMembershipPlanActionView,
    ChromeDevtoolsProbeView,
    CreateCheckoutSessionView,
    DeferPaymentView,
    PaymentMethodChoiceView,
    DashboardRedirectView,
    ExemptOrderActionView,
    FinancialControlView,
    MarkOrderPaidActionView,
    PaymentCancelView,
    PaymentSuccessView,
    PendingPaymentListView,
    RefundOrderActionView,
    RetryPendingOrderView,
    StripeWebhookView,
    AsaasWebhookView,
    CreatePixChargeView,
    PayoutApproveView,
    PayoutDispatchView,
    PayoutQueueView,
    PayoutRefuseView,
    PayrollListView,
    TeacherFinancialView,
    InstructorHomeView,
    PersonCreateView,
    PersonDeleteView,
    PersonDetailView,
    PersonListView,
    PersonTypeCreateView,
    PersonTypeDeleteView,
    PersonTypeDetailView,
    PersonTypeListView,
    PersonTypeUpdateView,
    PersonUpdateView,
    PlanCreateView,
    PlanDeleteView,
    PlanDetailView,
    PlanListView,
    PlanUpdateView,
    PortalLoginView,
    PortalLogoutView,
    ProductBackorderCreateView,
    PortalPasswordResetCompleteView,
    PortalPasswordResetConfirmView,
    PortalPasswordResetDoneView,
    PortalPasswordResetView,
    PortalRegisterView,
    RegistrationStepValidationView,
    CreateProductOrderView,
    PlanChangeConfirmView,
    PlanChangeSelectView,
    ProductCreateView,
    ProductDeleteView,
    ProductDetailView,
    ProductListView,
    ProductStoreView,
    ProductUpdateView,
    StudentBackorderCancelView,
    StudentBackorderConfirmView,
    StudentBackorderListView,
    StudentCheckinView,
    StudentHomeView,
    StudentOrderHistoryView,
    StudentScheduleView,
    StudentSpecialClassCheckinView,
)


app_name = "system"


urlpatterns = [
    path(".well-known/appspecific/com.chrome.devtools.json", ChromeDevtoolsProbeView.as_view(), name="chrome-devtools-probe"),
    path("", PortalLoginView.as_view(), name="root"),
    path("login/", PortalLoginView.as_view(), name="login"),
    path("register/", PortalRegisterView.as_view(), name="register"),
    path("register/validate-step/", RegistrationStepValidationView.as_view(), name="registration-step-validate"),
    path("password-reset/", PortalPasswordResetView.as_view(), name="password-reset"),
    path("password-reset/done/", PortalPasswordResetDoneView.as_view(), name="password-reset-done"),
    path("reset/done/", PortalPasswordResetCompleteView.as_view(), name="password-reset-complete"),
    path("reset/<str:token>/", PortalPasswordResetConfirmView.as_view(), name="password-reset-confirm"),
    path("logout/", PortalLogoutView.as_view(), name="logout"),
    path("dashboard/", DashboardRedirectView.as_view(), name="dashboard-redirect"),
    path("home/admin/", AdminHomeView.as_view(), name="admin-home"),
    path("home/administrative/", AdministrativeHomeView.as_view(), name="administrative-home"),
    path("home/instructor/", InstructorHomeView.as_view(), name="instructor-home"),
    path("home/student/", StudentHomeView.as_view(), name="student-home"),
    path("schedule/", StudentScheduleView.as_view(), name="student-schedule"),
    path("schedule/<int:year>/<int:month>/", StudentScheduleView.as_view(), name="student-schedule-month"),
    path("checkin/", StudentCheckinView.as_view(), name="student-checkin"),
    path("admin-calendar/", AdminCalendarView.as_view(), name="admin-calendar"),
    path("admin-calendar/<int:year>/<int:month>/", AdminCalendarView.as_view(), name="admin-calendar-month"),
    path("admin-calendar/toggle-session/", AdminToggleSessionView.as_view(), name="admin-toggle-session"),
    path("admin-calendar/special-class/create/", AdminSpecialClassCreateView.as_view(), name="admin-special-class-create"),
    path("admin-calendar/special-class/delete/", AdminSpecialClassDeleteView.as_view(), name="admin-special-class-delete"),
    path("special-checkin/", StudentSpecialClassCheckinView.as_view(), name="student-special-checkin"),
    path("instructor/approve-checkin/", InstructorApproveCheckinView.as_view(), name="instructor-approve-checkin"),
    path("instructor/approve-special-checkin/", InstructorApproveSpecialCheckinView.as_view(), name="instructor-approve-special-checkin"),
    path("instructor/calendar/", InstructorCalendarView.as_view(), name="instructor-calendar"),
    path("instructor/calendar/<int:year>/<int:month>/", InstructorCalendarView.as_view(), name="instructor-calendar-month"),
    path("instructor/calendar/toggle-session/", InstructorToggleSessionView.as_view(), name="instructor-toggle-session"),
    path("instructor/calendar/special-class/create/", InstructorSpecialClassCreateView.as_view(), name="instructor-special-class-create"),
    path("instructor/calendar/special-class/delete/", InstructorSpecialClassDeleteView.as_view(), name="instructor-special-class-delete"),
    path("class-categories/", ClassCategoryListView.as_view(), name="class-category-list"),
    path("class-categories/create/", ClassCategoryCreateView.as_view(), name="class-category-create"),
    path("class-categories/<int:pk>/", ClassCategoryDetailView.as_view(), name="class-category-detail"),
    path("class-categories/<int:pk>/edit/", ClassCategoryUpdateView.as_view(), name="class-category-update"),
    path("class-categories/<int:pk>/delete/", ClassCategoryDeleteView.as_view(), name="class-category-delete"),
    path("class-groups/", ClassGroupListView.as_view(), name="class-group-list"),
    path("class-groups/create/", ClassGroupCreateView.as_view(), name="class-group-create"),
    path("class-groups/<int:pk>/", ClassGroupDetailView.as_view(), name="class-group-detail"),
    path("class-groups/<int:pk>/edit/", ClassGroupUpdateView.as_view(), name="class-group-update"),
    path("class-groups/<int:pk>/delete/", ClassGroupDeleteView.as_view(), name="class-group-delete"),
    path("class-schedules/", ClassScheduleListView.as_view(), name="class-schedule-list"),
    path("class-schedules/create/", ClassScheduleCreateView.as_view(), name="class-schedule-create"),
    path("class-schedules/<int:pk>/", ClassScheduleDetailView.as_view(), name="class-schedule-detail"),
    path("class-schedules/<int:pk>/edit/", ClassScheduleUpdateView.as_view(), name="class-schedule-update"),
    path("class-schedules/<int:pk>/delete/", ClassScheduleDeleteView.as_view(), name="class-schedule-delete"),
    path("people/", PersonListView.as_view(), name="person-list"),
    path("people/create/", PersonCreateView.as_view(), name="person-create"),
    path("people/<int:pk>/", PersonDetailView.as_view(), name="person-detail"),
    path("people/<int:pk>/edit/", PersonUpdateView.as_view(), name="person-update"),
    path("people/<int:pk>/delete/", PersonDeleteView.as_view(), name="person-delete"),
    path("person-types/", PersonTypeListView.as_view(), name="person-type-list"),
    path("person-types/create/", PersonTypeCreateView.as_view(), name="person-type-create"),
    path("person-types/<int:pk>/", PersonTypeDetailView.as_view(), name="person-type-detail"),
    path("person-types/<int:pk>/edit/", PersonTypeUpdateView.as_view(), name="person-type-update"),
    path("person-types/<int:pk>/delete/", PersonTypeDeleteView.as_view(), name="person-type-delete"),
    path("plan-change/", PlanChangeSelectView.as_view(), name="plan-change-select"),
    path("plan-change/<int:plan_id>/confirm/", PlanChangeConfirmView.as_view(), name="plan-change-confirm"),
    path("plans/", PlanListView.as_view(), name="plan-list"),
    path("plans/create/", PlanCreateView.as_view(), name="plan-create"),
    path("plans/<int:pk>/", PlanDetailView.as_view(), name="plan-detail"),
    path("plans/<int:pk>/edit/", PlanUpdateView.as_view(), name="plan-update"),
    path("plans/<int:pk>/delete/", PlanDeleteView.as_view(), name="plan-delete"),
    path("store/", ProductStoreView.as_view(), name="product-store"),
    path("store/checkout/", CreateProductOrderView.as_view(), name="product-store-checkout"),
    path("store/backorders/create/", ProductBackorderCreateView.as_view(), name="product-backorder-create"),
    path("store/pedidos/", StudentBackorderListView.as_view(), name="student-backorders"),
    path("store/pedidos/<int:pk>/confirmar/", StudentBackorderConfirmView.as_view(), name="student-backorder-confirm"),
    path("store/pedidos/<int:pk>/cancelar/", StudentBackorderCancelView.as_view(), name="student-backorder-cancel"),
    path("store/historico/", StudentOrderHistoryView.as_view(), name="student-order-history"),
    path("billing/backorders/", AdminBackorderQueueView.as_view(), name="admin-backorder-queue"),
    path("products/", ProductListView.as_view(), name="product-list"),
    path("products/create/", ProductCreateView.as_view(), name="product-create"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="product-detail"),
    path("products/<int:pk>/edit/", ProductUpdateView.as_view(), name="product-update"),
    path("products/<int:pk>/delete/", ProductDeleteView.as_view(), name="product-delete"),
    path("payments/checkout/<int:order_id>/", PaymentMethodChoiceView.as_view(), name="payment-checkout"),
    path("payments/stripe/<int:order_id>/", CreateCheckoutSessionView.as_view(), name="stripe-checkout"),
    path("payments/defer/<int:order_id>/", DeferPaymentView.as_view(), name="payment-defer"),
    path("payments/retry/", RetryPendingOrderView.as_view(), name="payment-retry"),
    path("payments/success/", PaymentSuccessView.as_view(), name="payment-success"),
    path("payments/cancel/", PaymentCancelView.as_view(), name="payment-cancel"),
    path("payments/webhook/stripe/", StripeWebhookView.as_view(), name="stripe-webhook"),
    path("billing/approvals/", ApprovalQueueView.as_view(), name="approval-queue"),
    path("billing/pending/", PendingPaymentListView.as_view(), name="pending-payments"),
    path("billing/financial/", FinancialControlView.as_view(), name="financial-control"),
    path("billing/orders/<int:order_id>/exempt/", ExemptOrderActionView.as_view(), name="exempt-order"),
    path("billing/orders/<int:order_id>/mark-paid/", MarkOrderPaidActionView.as_view(), name="mark-order-paid"),
    path("billing/orders/<int:order_id>/refund/", RefundOrderActionView.as_view(), name="refund-order"),
    path("billing/memberships/<int:membership_id>/cancel/", CancelMembershipActionView.as_view(), name="cancel-membership"),
    path("billing/memberships/<int:membership_id>/change-plan/", ChangeMembershipPlanActionView.as_view(), name="change-plan"),
    path("payments/pix/create/<int:order_id>/", CreatePixChargeView.as_view(), name="asaas-pix-create"),
    path("payments/webhook/asaas/", AsaasWebhookView.as_view(), name="asaas-webhook"),
    path("billing/payroll/", PayrollListView.as_view(), name="payroll-list"),
    path("billing/payouts/", PayoutQueueView.as_view(), name="payout-queue"),
    path("billing/payouts/<int:payout_id>/approve/", PayoutApproveView.as_view(), name="payout-approve"),
    path("billing/payouts/<int:payout_id>/refuse/", PayoutRefuseView.as_view(), name="payout-refuse"),
    path("billing/payouts/<int:payout_id>/dispatch/", PayoutDispatchView.as_view(), name="payout-dispatch"),
    path("me/financeiro/", TeacherFinancialView.as_view(), name="teacher-financial"),
    path("graduation/overview/", GraduationOverviewView.as_view(), name="graduation-overview"),
    path("belt-ranks/", BeltRankListView.as_view(), name="belt-rank-list"),
    path("belt-ranks/create/", BeltRankCreateView.as_view(), name="belt-rank-create"),
    path("belt-ranks/<int:pk>/", BeltRankDetailView.as_view(), name="belt-rank-detail"),
    path("belt-ranks/<int:pk>/edit/", BeltRankUpdateView.as_view(), name="belt-rank-update"),
    path("belt-ranks/<int:pk>/delete/", BeltRankDeleteView.as_view(), name="belt-rank-delete"),
    path("graduation-rules/", GraduationRuleListView.as_view(), name="graduation-rule-list"),
    path("graduation-rules/create/", GraduationRuleCreateView.as_view(), name="graduation-rule-create"),
    path("graduation-rules/<int:pk>/edit/", GraduationRuleUpdateView.as_view(), name="graduation-rule-update"),
    path("graduation-rules/<int:pk>/delete/", GraduationRuleDeleteView.as_view(), name="graduation-rule-delete"),
    path("graduations/", GraduationListView.as_view(), name="graduation-list"),
    path("graduations/create/", GraduationCreateView.as_view(), name="graduation-create"),
    path("graduations/<int:pk>/delete/", GraduationDeleteView.as_view(), name="graduation-delete"),
]
