from django.urls import path

from system.core.health import CHROME_DEVTOOLS_PROBE_PATH, chrome_devtools_probe, health
from system.business_rule.views.auth_views import LoginView, LogoutView
from system.business_rule.views.home_views import HomeView
from system.business_rule.views.password_reset_views import (
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetRequestView,
    PasswordResetSentView,
)

app_name = "system"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("health/", health, name="health"),
    path(
        CHROME_DEVTOOLS_PROBE_PATH,
        chrome_devtools_probe,
        name="chrome-devtools-probe",
    ),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "password-reset/",
        PasswordResetRequestView.as_view(),
        name="password-reset",
    ),
    path(
        "password-reset/sent/",
        PasswordResetSentView.as_view(),
        name="password-reset-sent",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(),
        name="password-reset-done",
    ),
    path(
        "password-reset/<str:identifier>/<str:token>/",
        PasswordResetConfirmView.as_view(),
        name="password-reset-confirm",
    ),
]

# ----------------------------------------------------------------------------
# BN - business rule: rotas do produto. Acima desta linha esta a base de rotas
# e os imports que ela exige, com os mesmos nomes e na mesma ordem. Registro em
# obsidian/projetos/lvjiujitsu/.
# ----------------------------------------------------------------------------

from django.views.generic import RedirectView
from system.business_rule.views.auth_views import PortalChangePasswordView
from system.business_rule.views.registration_views import (
    FinalizeRegistrationView,
    MaterialsCheckoutView,
    PortalRegisterView,
    RegistrationCpfAvailabilityView,
    RegistrationEligibilityView,
    ResetRegistrationView,
    ValidateCouponView,
)
from system.business_rule.views.access_request_views import (
    AdministrativeAccessRequestDetailView,
    AdministrativeAccessRequestQueueView,
    AdministrativeAccessRequestSelfCancelView,
    PortalAdministrativeAccessRequestCreateView,
    PublicAdministrativeAccessRequestCreateView,
)
from system.business_rule.views.asaas_views import (
    AsaasWebhookView,
    CreateCreditCardChargeView,
    CreatePixChargeView,
    PayrollListView,
    PayoutApproveView,
    PayoutDispatchView,
    PayoutQueueView,
    PayoutRefuseView,
)
from system.business_rule.views.admin_views import AdminHubView, AuditLogListView, MembershipTimelineAdminListView
from system.business_rule.views.billing_admin_views import (
    ApprovalQueueView,
    CancelMembershipActionView,
    ChangeMembershipPlanActionView,
    ExemptOrderActionView,
    FinancialControlView,
    MarkOrderPaidActionView,
    PendingPaymentListView,
    RefundOrderActionView,
)
from system.business_rule.views.category_views import (
    ClassCategoryCreateView,
    ClassCategoryDeleteView,
    ClassCategoryDetailView,
    ClassCategoryListView,
    ClassCategoryUpdateView,
)
from system.business_rule.views.class_views import (
    ClassGroupCreateView,
    ClassGroupDeleteView,
    ClassGroupDetailView,
    ClassGroupListView,
    ClassGroupUpdateView,
    ClassScheduleCreateView,
    ClassScheduleDeleteView,
    ClassScheduleDetailView,
    ClassScheduleListView,
    ClassScheduleUpdateView,
)
from system.business_rule.views.class_request_views import (
    ClassCatalogRequestDetailView,
    ClassCatalogRequestQueueView,
    ClassCatalogRequestSelfCancelView,
    ExistingTeacherClassCatalogRequestCreateView,
    PublicNewTeacherClassCatalogRequestCreateView,
)
from system.business_rule.views.graduation_views import (
    BeltRankCreateView,
    BeltRankDeleteView,
    BeltRankDetailView,
    BeltRankListView,
    BeltRankUpdateView,
    GraduationCreateView,
    GraduationDeleteView,
    GraduationListView,
    GraduationOverviewView,
    GraduationRuleCreateView,
    GraduationRuleDeleteView,
    GraduationRuleListView,
    GraduationRuleUpdateView,
)
from system.business_rule.views.stripe_views import StripeWebhookView
from system.business_rule.views.home_views import (
    ClientProfileDeactivateView,
    ClientProfileUpdateView,
    DashboardRedirectView,
)
from system.business_rule.views.dependent_views import (
    DependentProfileUpdateView,
    DependentRegistrationView,
    DependentRemoveView,
)
from system.business_rule.views.person_views import (
    PersonCreateView,
    PersonDeleteView,
    PersonDetailView,
    PersonListView,
    PersonTypeCreateView,
    PersonTypeDeleteView,
    PersonTypeDetailView,
    PersonTypeListView,
    PersonTypeUpdateView,
    PersonUpdateView,
    VeteranPlanDecisionView,
)
from system.business_rule.views.plan_views import (
    PlanCreateView,
    PlanDeleteView,
    PlanDetailView,
    PlanListView,
    PlanUpdateView,
)
from system.business_rule.views.plan_tier_views import (
    PlanPriceCreateView,
    PlanPriceDeleteView,
    PlanPriceUpdateView,
    PlanTierCreateView,
    PlanTierDeleteView,
    PlanTierDetailView,
    PlanTierListView,
    PlanTierUpdateView,
)
from system.business_rule.views.plan_change_views import MembershipUpdateCardView, PlanChangeSelectView
from system.business_rule.views.membership_pause_views import (
    MembershipPauseQuotaView,
    MembershipPauseRequestCreateView,
    MembershipPauseRequestDetailView,
    MembershipPauseRequestQueueView,
)
from system.business_rule.views.calendar_views import (
    CalendarView,
    InstructorApproveCheckinView,
    InstructorApproveSpecialCheckinView,
    InstructorSelfCheckinView,
    InstructorSelfCheckinCancelView,
    InstructorSelfSpecialCheckinView,
    InstructorSelfSpecialCheckinCancelView,
    InstructorCancelClassTodayView,
    InstructorSessionSubstituteView,
    InstructorSpecialClassCreateView,
    InstructorSpecialClassDeleteView,
    InstructorToggleSessionView,
    StudentCheckinCancelView,
    StudentCheckinView,
    StudentSpecialClassCheckinCancelView,
    StudentSpecialClassCheckinView,
)
from system.business_rule.views.payment_views import (
    DeferPaymentView,
    PaymentCancelView,
    PaymentMethodChoiceView,
    PaymentSuccessView,
    RetryPendingOrderView,
)
from system.business_rule.views.product_views import (
    AdminBackorderQueueView,
    CreateProductOrderView,
    ProductBackorderCreateView,
    ProductCategoryCreateView,
    ProductCategoryDeleteView,
    ProductCategoryDetailView,
    ProductCategoryListView,
    ProductCategoryUpdateView,
    ProductCreateView,
    ProductDeleteView,
    ProductDetailView,
    ProductListView,
    ProductStoreView,
    ProductUpdateView,
    StudentBackorderCancelView,
    StudentBackorderConfirmView,
    StudentBackorderListView,
    StudentOrderHistoryView,
)

urlpatterns += [
    path("register/", PortalRegisterView.as_view(), name="register"),
    path("register/admin-access/", PublicAdministrativeAccessRequestCreateView.as_view(), name="administrative-access-public-create"),
    path("register/teacher-proposal/", PublicNewTeacherClassCatalogRequestCreateView.as_view(), name="class-catalog-request-public-teacher-create"),
    path("register/check-cpf/", RegistrationCpfAvailabilityView.as_view(), name="register-check-cpf"),
    path("registration/validate-coupon/", ValidateCouponView.as_view(), name="validate-coupon"),
    path("registration/eligibility/", RegistrationEligibilityView.as_view(), name="registration-eligibility"),
    path("register/materiais/", MaterialsCheckoutView.as_view(), name="register-materials-checkout"),
    path("register/finalizar/", FinalizeRegistrationView.as_view(), name="register-finalize"),
    path("register/recomecar/", ResetRegistrationView.as_view(), name="register-reset"),
    path("payments/<int:order_id>/", PaymentMethodChoiceView.as_view(), name="payment-checkout"),
    path("payments/<int:order_id>/asaas-pix/", CreatePixChargeView.as_view(), name="asaas-pix-create"),
    path("payments/<int:order_id>/asaas-card/", CreateCreditCardChargeView.as_view(), name="asaas-card-create"),
    path("payments/<int:order_id>/pay-later/", DeferPaymentView.as_view(), name="payment-defer"),
    path("payments/pending/", RetryPendingOrderView.as_view(), name="payment-retry"),
    path("my-membership/change-plan/", PlanChangeSelectView.as_view(), name="plan-change-select"),
    path("my-membership/change-card/", MembershipUpdateCardView.as_view(), name="membership-update-card"),
    path("my-membership/pause/", MembershipPauseRequestCreateView.as_view(), name="membership-pause-request-create"),
    path("my-membership/pause/quota/", MembershipPauseQuotaView.as_view(), name="membership-pause-quota"),
    path("requests/pausas/", MembershipPauseRequestQueueView.as_view(), name="membership-pause-request-list"),
    path("requests/pausas/<int:pk>/", MembershipPauseRequestDetailView.as_view(), name="membership-pause-request-detail"),
    path("payments/success/", PaymentSuccessView.as_view(), name="payment-success"),
    path("payments/cancelled/", PaymentCancelView.as_view(), name="payment-cancel"),
    path("payments/webhook/asaas/", AsaasWebhookView.as_view(), name="asaas-webhook"),
    path("payments/webhook/stripe/", StripeWebhookView.as_view(), name="stripe-webhook"),
    path("password-change/", PortalChangePasswordView.as_view(), name="password-change"),
    path("dashboard/", DashboardRedirectView.as_view(), name="dashboard-redirect"),
    path("account/profile/update/", ClientProfileUpdateView.as_view(), name="client-profile-update"),
    path("account/profile/deactivate/", ClientProfileDeactivateView.as_view(), name="client-profile-deactivate"),
    path("dependents/add/", DependentRegistrationView.as_view(), name="dependent-add"),
    path("dependents/<int:pk>/profile/update/", DependentProfileUpdateView.as_view(), name="dependent-profile-update"),
    path("dependents/<int:pk>/remove/", DependentRemoveView.as_view(), name="dependent-remove"),
    path("requests/admin-access/create/", PortalAdministrativeAccessRequestCreateView.as_view(), name="administrative-access-request-create"),
    path("requests/admin-access/", AdministrativeAccessRequestQueueView.as_view(), name="administrative-access-request-list"),
    path("requests/admin-access/<int:pk>/", AdministrativeAccessRequestDetailView.as_view(), name="administrative-access-request-detail"),
    path("requests/admin-access/<int:pk>/cancel/", AdministrativeAccessRequestSelfCancelView.as_view(), name="administrative-access-request-self-cancel"),
    path("requests/classes/create/", ExistingTeacherClassCatalogRequestCreateView.as_view(), name="class-catalog-request-create"),
    path("requests/classes/", ClassCatalogRequestQueueView.as_view(), name="class-catalog-request-list"),
    path("requests/classes/<int:pk>/", ClassCatalogRequestDetailView.as_view(), name="class-catalog-request-detail"),
    path("requests/classes/<int:pk>/cancel/", ClassCatalogRequestSelfCancelView.as_view(), name="class-catalog-request-self-cancel"),
    path("people/", PersonListView.as_view(), name="person-list"),
    path("people/create/", PersonCreateView.as_view(), name="person-create"),
    path("people/<int:pk>/view/", PersonDetailView.as_view(), name="person-detail"),
    path("people/<int:pk>/edit/", PersonUpdateView.as_view(), name="person-update"),
    path("people/<int:pk>/delete/", PersonDeleteView.as_view(), name="person-delete"),
    path(
        "people/<int:pk>/veteran-plan/",
        VeteranPlanDecisionView.as_view(),
        name="person-veteran-plan-decision",
    ),
    path("pessoas/", RedirectView.as_view(pattern_name="system:person-list", permanent=False)),
    path("pessoas/nova/", RedirectView.as_view(pattern_name="system:person-create", permanent=False)),
    path("pessoas/<int:pk>/", RedirectView.as_view(pattern_name="system:person-detail", permanent=False)),
    path("pessoas/<int:pk>/editar/", RedirectView.as_view(pattern_name="system:person-update", permanent=False)),
    path("pessoas/<int:pk>/excluir/", RedirectView.as_view(pattern_name="system:person-delete", permanent=False)),
    path("plans/", PlanListView.as_view(), name="plan-list"),
    path("plans/create/", PlanCreateView.as_view(), name="plan-create"),
    path("plans/<int:pk>/view/", PlanDetailView.as_view(), name="plan-detail"),
    path("plans/<int:pk>/edit/", PlanUpdateView.as_view(), name="plan-update"),
    path("plans/<int:pk>/delete/", PlanDeleteView.as_view(), name="plan-delete"),
    path("plan-tiers/", PlanTierListView.as_view(), name="plan-tier-list"),
    path("plan-tiers/create/", PlanTierCreateView.as_view(), name="plan-tier-create"),
    path("plan-tiers/<int:pk>/view/", PlanTierDetailView.as_view(), name="plan-tier-detail"),
    path("plan-tiers/<int:pk>/edit/", PlanTierUpdateView.as_view(), name="plan-tier-update"),
    path("plan-tiers/<int:pk>/delete/", PlanTierDeleteView.as_view(), name="plan-tier-delete"),
    path(
        "plan-tiers/<int:tier_pk>/prices/create/",
        PlanPriceCreateView.as_view(),
        name="plan-price-create",
    ),
    path("plan-prices/<int:pk>/edit/", PlanPriceUpdateView.as_view(), name="plan-price-update"),
    path("plan-prices/<int:pk>/delete/", PlanPriceDeleteView.as_view(), name="plan-price-delete"),
    path("planos/", RedirectView.as_view(pattern_name="system:plan-list", permanent=False)),
    path("planos/novo/", RedirectView.as_view(pattern_name="system:plan-create", permanent=False)),
    path("planos/<int:pk>/", RedirectView.as_view(pattern_name="system:plan-detail", permanent=False)),
    path("planos/<int:pk>/editar/", RedirectView.as_view(pattern_name="system:plan-update", permanent=False)),
    path("planos/<int:pk>/excluir/", RedirectView.as_view(pattern_name="system:plan-delete", permanent=False)),
    path("administration/", AdminHubView.as_view(), name="admin-hub"),
    path("administration/audit/", AuditLogListView.as_view(), name="audit-log-list"),
    path("administration/historico-assinaturas/", MembershipTimelineAdminListView.as_view(), name="membership-timeline-admin-list"),
    path("administration/person-types/", PersonTypeListView.as_view(), name="person-type-list"),
    path("administration/person-types/create/", PersonTypeCreateView.as_view(), name="person-type-create"),
    path("administration/person-types/<int:pk>/view/", PersonTypeDetailView.as_view(), name="person-type-detail"),
    path("administration/person-types/<int:pk>/edit/", PersonTypeUpdateView.as_view(), name="person-type-update"),
    path("administration/person-types/<int:pk>/delete/", PersonTypeDeleteView.as_view(), name="person-type-delete"),
    path("administracao/", RedirectView.as_view(pattern_name="system:admin-hub", permanent=False)),
    path("administracao/perfis/", RedirectView.as_view(pattern_name="system:person-type-list", permanent=False)),
    path("administracao/perfis/novo/", RedirectView.as_view(pattern_name="system:person-type-create", permanent=False)),
    path("administracao/perfis/<int:pk>/", RedirectView.as_view(pattern_name="system:person-type-detail", permanent=False)),
    path("administracao/perfis/<int:pk>/editar/", RedirectView.as_view(pattern_name="system:person-type-update", permanent=False)),
    path("administracao/perfis/<int:pk>/excluir/", RedirectView.as_view(pattern_name="system:person-type-delete", permanent=False)),
    path("classes/", ClassGroupListView.as_view(), name="class-group-list"),
    path("classes/create/", ClassGroupCreateView.as_view(), name="class-group-create"),
    path("classes/<int:pk>/view/", ClassGroupDetailView.as_view(), name="class-group-detail"),
    path("classes/<int:pk>/edit/", ClassGroupUpdateView.as_view(), name="class-group-update"),
    path("classes/<int:pk>/delete/", ClassGroupDeleteView.as_view(), name="class-group-delete"),
    path("classes/categories/", ClassCategoryListView.as_view(), name="class-category-list"),
    path("classes/categories/create/", ClassCategoryCreateView.as_view(), name="class-category-create"),
    path("classes/categories/<int:pk>/view/", ClassCategoryDetailView.as_view(), name="class-category-detail"),
    path("classes/categories/<int:pk>/edit/", ClassCategoryUpdateView.as_view(), name="class-category-update"),
    path("classes/categories/<int:pk>/delete/", ClassCategoryDeleteView.as_view(), name="class-category-delete"),
    path("classes/schedules/", ClassScheduleListView.as_view(), name="class-schedule-list"),
    path("classes/schedules/create/", ClassScheduleCreateView.as_view(), name="class-schedule-create"),
    path("classes/schedules/<int:pk>/view/", ClassScheduleDetailView.as_view(), name="class-schedule-detail"),
    path("classes/schedules/<int:pk>/edit/", ClassScheduleUpdateView.as_view(), name="class-schedule-update"),
    path("classes/schedules/<int:pk>/delete/", ClassScheduleDeleteView.as_view(), name="class-schedule-delete"),
    path("turmas/", RedirectView.as_view(pattern_name="system:class-group-list", permanent=False)),
    path("turmas/nova/", RedirectView.as_view(pattern_name="system:class-group-create", permanent=False)),
    path("turmas/<int:pk>/", RedirectView.as_view(pattern_name="system:class-group-detail", permanent=False)),
    path("turmas/<int:pk>/editar/", RedirectView.as_view(pattern_name="system:class-group-update", permanent=False)),
    path("turmas/<int:pk>/excluir/", RedirectView.as_view(pattern_name="system:class-group-delete", permanent=False)),
    path("turmas/categorias/", RedirectView.as_view(pattern_name="system:class-category-list", permanent=False)),
    path("turmas/categorias/nova/", RedirectView.as_view(pattern_name="system:class-category-create", permanent=False)),
    path("turmas/categorias/<int:pk>/", RedirectView.as_view(pattern_name="system:class-category-detail", permanent=False)),
    path("turmas/categorias/<int:pk>/editar/", RedirectView.as_view(pattern_name="system:class-category-update", permanent=False)),
    path("turmas/categorias/<int:pk>/excluir/", RedirectView.as_view(pattern_name="system:class-category-delete", permanent=False)),
    path("turmas/horarios/", RedirectView.as_view(pattern_name="system:class-schedule-list", permanent=False)),
    path("turmas/horarios/novo/", RedirectView.as_view(pattern_name="system:class-schedule-create", permanent=False)),
    path("turmas/horarios/<int:pk>/", RedirectView.as_view(pattern_name="system:class-schedule-detail", permanent=False)),
    path("turmas/horarios/<int:pk>/editar/", RedirectView.as_view(pattern_name="system:class-schedule-update", permanent=False)),
    path("turmas/horarios/<int:pk>/excluir/", RedirectView.as_view(pattern_name="system:class-schedule-delete", permanent=False)),
    path("financial/", FinancialControlView.as_view(), name="financial-control"),
    path("financial/approvals/", ApprovalQueueView.as_view(), name="approval-queue"),
    path("financial/pending/", PendingPaymentListView.as_view(), name="pending-payments"),
    path("financial/payroll/", PayrollListView.as_view(), name="payroll-list"),
    path("financial/payouts/", PayoutQueueView.as_view(), name="payout-queue"),
    path("financial/orders/<int:order_id>/exempt/", ExemptOrderActionView.as_view(), name="exempt-order"),
    path("financial/orders/<int:order_id>/mark-paid/", MarkOrderPaidActionView.as_view(), name="mark-order-paid"),
    path("financial/orders/<int:order_id>/refund/", RefundOrderActionView.as_view(), name="refund-order"),
    path("financial/memberships/<int:membership_id>/cancel/", CancelMembershipActionView.as_view(), name="cancel-membership"),
    path("financial/memberships/<int:membership_id>/change-plan/", ChangeMembershipPlanActionView.as_view(), name="change-membership-plan"),
    path("financial/payouts/<int:payout_id>/approve/", PayoutApproveView.as_view(), name="payout-approve"),
    path("financial/payouts/<int:payout_id>/refuse/", PayoutRefuseView.as_view(), name="payout-refuse"),
    path("financial/payouts/<int:payout_id>/dispatch/", PayoutDispatchView.as_view(), name="payout-dispatch"),
    path("financial/", RedirectView.as_view(pattern_name="system:financial-control", permanent=False)),
    path("financial/approvals/", RedirectView.as_view(pattern_name="system:approval-queue", permanent=False)),
    path("financial/pending/", RedirectView.as_view(pattern_name="system:pending-payments", permanent=False)),
    path("financial/payroll/", RedirectView.as_view(pattern_name="system:payroll-list", permanent=False)),
    path("financial/payouts/", RedirectView.as_view(pattern_name="system:payout-queue", permanent=False)),
    path("graduation/", GraduationOverviewView.as_view(), name="graduation-overview"),
    path("graduation/belt-ranks/", BeltRankListView.as_view(), name="belt-rank-list"),
    path("graduation/belt-ranks/create/", BeltRankCreateView.as_view(), name="belt-rank-create"),
    path("graduation/belt-ranks/<int:pk>/view/", BeltRankDetailView.as_view(), name="belt-rank-detail"),
    path("graduation/belt-ranks/<int:pk>/edit/", BeltRankUpdateView.as_view(), name="belt-rank-update"),
    path("graduation/belt-ranks/<int:pk>/delete/", BeltRankDeleteView.as_view(), name="belt-rank-delete"),
    path("graduation/rules/", GraduationRuleListView.as_view(), name="graduation-rule-list"),
    path("graduation/rules/create/", GraduationRuleCreateView.as_view(), name="graduation-rule-create"),
    path("graduation/rules/<int:pk>/edit/", GraduationRuleUpdateView.as_view(), name="graduation-rule-update"),
    path("graduation/rules/<int:pk>/delete/", GraduationRuleDeleteView.as_view(), name="graduation-rule-delete"),
    path("graduation/history/", GraduationListView.as_view(), name="graduation-list"),
    path("graduation/history/create/", GraduationCreateView.as_view(), name="graduation-create"),
    path("graduation/history/<int:pk>/delete/", GraduationDeleteView.as_view(), name="graduation-delete"),
    path("graduacao/", RedirectView.as_view(pattern_name="system:graduation-overview", permanent=False)),
    path("graduacao/faixas/", RedirectView.as_view(pattern_name="system:belt-rank-list", permanent=False)),
    path("graduacao/faixas/nova/", RedirectView.as_view(pattern_name="system:belt-rank-create", permanent=False)),
    path("graduacao/faixas/<int:pk>/", RedirectView.as_view(pattern_name="system:belt-rank-detail", permanent=False)),
    path("graduacao/faixas/<int:pk>/editar/", RedirectView.as_view(pattern_name="system:belt-rank-update", permanent=False)),
    path("graduacao/faixas/<int:pk>/excluir/", RedirectView.as_view(pattern_name="system:belt-rank-delete", permanent=False)),
    path("graduacao/regras/", RedirectView.as_view(pattern_name="system:graduation-rule-list", permanent=False)),
    path("graduacao/regras/nova/", RedirectView.as_view(pattern_name="system:graduation-rule-create", permanent=False)),
    path("graduacao/regras/<int:pk>/editar/", RedirectView.as_view(pattern_name="system:graduation-rule-update", permanent=False)),
    path("graduacao/regras/<int:pk>/excluir/", RedirectView.as_view(pattern_name="system:graduation-rule-delete", permanent=False)),
    path("graduacao/historico/", RedirectView.as_view(pattern_name="system:graduation-list", permanent=False)),
    path("graduacao/historico/novo/", RedirectView.as_view(pattern_name="system:graduation-create", permanent=False)),
    path("graduacao/historico/<int:pk>/excluir/", RedirectView.as_view(pattern_name="system:graduation-delete", permanent=False)),
    path("materials/", ProductListView.as_view(), name="product-list"),
    path("materials/create/", ProductCreateView.as_view(), name="product-create"),
    path("materials/<int:pk>/view/", ProductDetailView.as_view(), name="product-detail"),
    path("materials/<int:pk>/edit/", ProductUpdateView.as_view(), name="product-update"),
    path("materials/<int:pk>/delete/", ProductDeleteView.as_view(), name="product-delete"),
    path("materials/backorders/", AdminBackorderQueueView.as_view(), name="admin-backorder-queue"),
    path("materials/categories/", ProductCategoryListView.as_view(), name="product-category-list"),
    path("materials/categories/create/", ProductCategoryCreateView.as_view(), name="product-category-create"),
    path("materials/categories/<int:pk>/view/", ProductCategoryDetailView.as_view(), name="product-category-detail"),
    path("materials/categories/<int:pk>/edit/", ProductCategoryUpdateView.as_view(), name="product-category-update"),
    path("materials/categories/<int:pk>/delete/", ProductCategoryDeleteView.as_view(), name="product-category-delete"),
    path("store/", ProductStoreView.as_view(), name="product-store"),
    path("store/buy/", CreateProductOrderView.as_view(), name="product-order-create"),
    path("store/backorder/", ProductBackorderCreateView.as_view(), name="product-backorder-create"),
    path("my-materials/backorders/", StudentBackorderListView.as_view(), name="student-backorders"),
    path("my-materials/backorders/<int:pk>/confirm/", StudentBackorderConfirmView.as_view(), name="student-backorder-confirm"),
    path("my-materials/backorders/<int:pk>/cancel/", StudentBackorderCancelView.as_view(), name="student-backorder-cancel"),
    path("my-materials/orders/", StudentOrderHistoryView.as_view(), name="student-order-history"),
    path("materiais/", RedirectView.as_view(pattern_name="system:product-list", permanent=False)),
    path("materiais/novo/", RedirectView.as_view(pattern_name="system:product-create", permanent=False)),
    path("materiais/<int:pk>/", RedirectView.as_view(pattern_name="system:product-detail", permanent=False)),
    path("materiais/<int:pk>/editar/", RedirectView.as_view(pattern_name="system:product-update", permanent=False)),
    path("materiais/<int:pk>/excluir/", RedirectView.as_view(pattern_name="system:product-delete", permanent=False)),
    path("materiais/pre-pedidos/", RedirectView.as_view(pattern_name="system:admin-backorder-queue", permanent=False)),
    path("loja/", RedirectView.as_view(pattern_name="system:product-store", permanent=False)),
    path("loja/comprar/", RedirectView.as_view(pattern_name="system:product-order-create", permanent=False)),
    path("loja/pre-pedido/", RedirectView.as_view(pattern_name="system:product-backorder-create", permanent=False)),
    path("meus-materiais/pre-pedidos/", RedirectView.as_view(pattern_name="system:student-backorders", permanent=False)),
    path("meus-materiais/pedidos/", RedirectView.as_view(pattern_name="system:student-order-history", permanent=False)),
    path("classes/checkin/", StudentCheckinView.as_view(), name="student-checkin"),
    path("classes/checkin/cancel/", StudentCheckinCancelView.as_view(), name="student-checkin-cancel"),
    path("classes/special/checkin/", StudentSpecialClassCheckinView.as_view(), name="student-special-checkin"),
    path("classes/special/checkin/cancel/", StudentSpecialClassCheckinCancelView.as_view(), name="student-special-checkin-cancel"),
    path("classes/instructor/attendance/", InstructorSelfCheckinView.as_view(), name="instructor-self-checkin"),
    path("classes/instructor/attendance/cancel/", InstructorSelfCheckinCancelView.as_view(), name="instructor-self-checkin-cancel"),
    path("classes/instructor/substitute/", InstructorSessionSubstituteView.as_view(), name="instructor-session-substitute"),
    path("classes/instructor/session/cancel/", InstructorCancelClassTodayView.as_view(), name="instructor-cancel-class-today"),
    path("classes/instructor/special-attendance/", InstructorSelfSpecialCheckinView.as_view(), name="instructor-self-special-checkin"),
    path("classes/instructor/special-attendance/cancel/", InstructorSelfSpecialCheckinCancelView.as_view(), name="instructor-self-special-checkin-cancel"),
    path("classes/instructor/approve/", InstructorApproveCheckinView.as_view(), name="instructor-approve-checkin"),
    path("classes/instructor/approve-special/", InstructorApproveSpecialCheckinView.as_view(), name="instructor-approve-special-checkin"),
    path("classes/instructor/cancel/", InstructorToggleSessionView.as_view(), name="instructor-toggle-session"),
    path("classes/special/create/", InstructorSpecialClassCreateView.as_view(), name="instructor-special-class-create"),
    path("classes/special/delete/", InstructorSpecialClassDeleteView.as_view(), name="instructor-special-class-delete"),
    path("calendar/", CalendarView.as_view(), name="calendar"),
    path("calendar/<int:year>/<int:month>/", CalendarView.as_view(), name="calendar-month"),
    path("cronograma/", RedirectView.as_view(pattern_name="system:calendar", permanent=False)),
]
