from django.urls import path

from system.views import (
    AdminCalendarView,
    AdminHomeView,
    AdminToggleSessionView,
    AdministrativeHomeView,
    ClassCategoryCreateView,
    ClassCategoryDeleteView,
    ClassCategoryDetailView,
    ClassCategoryListView,
    ClassCategoryUpdateView,
    ClassGroupCreateView,
    ClassGroupDeleteView,
    ClassGroupDetailView,
    ClassGroupListView,
    ClassGroupUpdateView,
    ClassScheduleCreateView,
    ClassScheduleDeleteView,
    ClassScheduleDetailView,
    ClassScheduleListView,
    ClassScheduleUpdateView,
    ChromeDevtoolsProbeView,
    DashboardRedirectView,
    InstructorHomeView,
    PersonCreateView,
    PersonDeleteView,
    PersonDetailView,
    PersonListView,
    PersonTypeCreateView,
    PersonTypeDeleteView,
    PersonTypeDetailView,
    PersonTypeListView,
    PersonTypeUpdateView,
    PortalHomeView,
    PortalInfoView,
    PersonUpdateView,
    PlanCatalogView,
    PlanCreateView,
    PlanDeleteView,
    PlanDetailView,
    PlanListView,
    PlanUpdateView,
    PortalLoginView,
    PortalLogoutView,
    PortalPasswordResetCompleteView,
    PortalPasswordResetConfirmView,
    PortalPasswordResetDoneView,
    PortalPasswordResetView,
    PortalRegisterView,
    ProductCatalogView,
    ProductCreateView,
    ProductDeleteView,
    ProductDetailView,
    ProductListView,
    ProductUpdateView,
    StudentCheckinView,
    StudentHomeView,
    StudentScheduleView,
)


app_name = "system"


urlpatterns = [
    path(".well-known/appspecific/com.chrome.devtools.json", ChromeDevtoolsProbeView.as_view(), name="chrome-devtools-probe"),
    path("", PortalHomeView.as_view(), name="root"),
    path("login/", PortalLoginView.as_view(), name="login"),
    path("register/", PortalRegisterView.as_view(), name="register"),
    path("info/", PortalInfoView.as_view(), name="info"),
    path("password-reset/", PortalPasswordResetView.as_view(), name="password-reset"),
    path("password-reset/done/", PortalPasswordResetDoneView.as_view(), name="password-reset-done"),
    path("reset/done/", PortalPasswordResetCompleteView.as_view(), name="password-reset-complete"),
    path("reset/<str:token>/", PortalPasswordResetConfirmView.as_view(), name="password-reset-confirm"),
    path("templates/login/login.html", PortalHomeView.as_view(), name="legacy-home"),
    path("templates/login/login-form.html", PortalLoginView.as_view(), name="legacy-login-form"),
    path("templates/login/cadastro.html", PortalRegisterView.as_view(), name="legacy-register"),
    path("templates/login/informacoes.html", PortalInfoView.as_view(), name="legacy-info"),
    path("logout/", PortalLogoutView.as_view(), name="logout"),
    path("dashboard/", DashboardRedirectView.as_view(), name="dashboard-redirect"),
    path("home/admin/", AdminHomeView.as_view(), name="admin-home"),
    path("home/administrative/", AdministrativeHomeView.as_view(), name="administrative-home"),
    path("home/instructor/", InstructorHomeView.as_view(), name="instructor-home"),
    path("home/student/", StudentHomeView.as_view(), name="student-home"),
    path("schedule/", StudentScheduleView.as_view(), name="student-schedule"),
    path("schedule/<int:year>/<int:month>/", StudentScheduleView.as_view(), name="student-schedule-month"),
    path("checkin/", StudentCheckinView.as_view(), name="student-checkin"),
    path("admin-calendar/", AdminCalendarView.as_view(), name="admin-calendar"),
    path("admin-calendar/<int:year>/<int:month>/", AdminCalendarView.as_view(), name="admin-calendar-month"),
    path("admin-calendar/toggle-session/", AdminToggleSessionView.as_view(), name="admin-toggle-session"),
    path("class-categories/", ClassCategoryListView.as_view(), name="class-category-list"),
    path("class-categories/create/", ClassCategoryCreateView.as_view(), name="class-category-create"),
    path("class-categories/<int:pk>/", ClassCategoryDetailView.as_view(), name="class-category-detail"),
    path("class-categories/<int:pk>/edit/", ClassCategoryUpdateView.as_view(), name="class-category-update"),
    path("class-categories/<int:pk>/delete/", ClassCategoryDeleteView.as_view(), name="class-category-delete"),
    path("class-groups/", ClassGroupListView.as_view(), name="class-group-list"),
    path("class-groups/create/", ClassGroupCreateView.as_view(), name="class-group-create"),
    path("class-groups/<int:pk>/", ClassGroupDetailView.as_view(), name="class-group-detail"),
    path("class-groups/<int:pk>/edit/", ClassGroupUpdateView.as_view(), name="class-group-update"),
    path("class-groups/<int:pk>/delete/", ClassGroupDeleteView.as_view(), name="class-group-delete"),
    path("class-schedules/", ClassScheduleListView.as_view(), name="class-schedule-list"),
    path("class-schedules/create/", ClassScheduleCreateView.as_view(), name="class-schedule-create"),
    path("class-schedules/<int:pk>/", ClassScheduleDetailView.as_view(), name="class-schedule-detail"),
    path("class-schedules/<int:pk>/edit/", ClassScheduleUpdateView.as_view(), name="class-schedule-update"),
    path("class-schedules/<int:pk>/delete/", ClassScheduleDeleteView.as_view(), name="class-schedule-delete"),
    path("people/", PersonListView.as_view(), name="person-list"),
    path("people/create/", PersonCreateView.as_view(), name="person-create"),
    path("people/<int:pk>/", PersonDetailView.as_view(), name="person-detail"),
    path("people/<int:pk>/edit/", PersonUpdateView.as_view(), name="person-update"),
    path("people/<int:pk>/delete/", PersonDeleteView.as_view(), name="person-delete"),
    path("person-types/", PersonTypeListView.as_view(), name="person-type-list"),
    path("person-types/create/", PersonTypeCreateView.as_view(), name="person-type-create"),
    path("person-types/<int:pk>/", PersonTypeDetailView.as_view(), name="person-type-detail"),
    path("person-types/<int:pk>/edit/", PersonTypeUpdateView.as_view(), name="person-type-update"),
    path("person-types/<int:pk>/delete/", PersonTypeDeleteView.as_view(), name="person-type-delete"),
    path("plans-catalog/", PlanCatalogView.as_view(), name="plan-catalog"),
    path("plans/", PlanListView.as_view(), name="plan-list"),
    path("plans/create/", PlanCreateView.as_view(), name="plan-create"),
    path("plans/<int:pk>/", PlanDetailView.as_view(), name="plan-detail"),
    path("plans/<int:pk>/edit/", PlanUpdateView.as_view(), name="plan-update"),
    path("plans/<int:pk>/delete/", PlanDeleteView.as_view(), name="plan-delete"),
    path("materials/", ProductCatalogView.as_view(), name="product-catalog"),
    path("products/", ProductListView.as_view(), name="product-list"),
    path("products/create/", ProductCreateView.as_view(), name="product-create"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="product-detail"),
    path("products/<int:pk>/edit/", ProductUpdateView.as_view(), name="product-update"),
    path("products/<int:pk>/delete/", ProductDeleteView.as_view(), name="product-delete"),
]
