from .auth_views import (
    ChromeDevtoolsProbeView,
    PortalHomeView,
    PortalInfoView,
    PortalLoginView,
    PortalLogoutView,
    PortalPasswordResetCompleteView,
    PortalPasswordResetConfirmView,
    PortalPasswordResetDoneView,
    PortalPasswordResetView,
    PortalRegisterView,
)
from .home_views import (
    AdminHomeView,
    AdministrativeHomeView,
    DashboardRedirectView,
    InstructorHomeView,
    RootRedirectView,
    StudentHomeView,
)
from .person_views import (
    PersonCreateView,
    PersonDeleteView,
    PersonListView,
    PersonTypeCreateView,
    PersonTypeDeleteView,
    PersonTypeListView,
    PersonTypeUpdateView,
    PersonUpdateView,
)

__all__ = [
    "AdminHomeView",
    "AdministrativeHomeView",
    "ChromeDevtoolsProbeView",
    "DashboardRedirectView",
    "InstructorHomeView",
    "PersonCreateView",
    "PersonDeleteView",
    "PersonListView",
    "PersonTypeCreateView",
    "PersonTypeDeleteView",
    "PersonTypeListView",
    "PersonTypeUpdateView",
    "PortalHomeView",
    "PortalInfoView",
    "PersonUpdateView",
    "PortalLoginView",
    "PortalLogoutView",
    "PortalPasswordResetCompleteView",
    "PortalPasswordResetConfirmView",
    "PortalPasswordResetDoneView",
    "PortalPasswordResetView",
    "PortalRegisterView",
    "RootRedirectView",
    "StudentHomeView",
]
